name = "FiniteHorizonGramians"
uuid = "c6e433de-f42a-4c21-b5ac-e7bc929bdc49"
authors = ["Filip Tronarp <filip.tronarp@matstat.lu.se> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
