name = "FiniteHorizonGramians"
uuid = "b59a298d-d283-4a37-9369-85a9f9a111a5"
authors = ["Filip Tronarp <filip.tronarp@matstat.lu.se>", "Tony Stillfjord <tony.stillfjord@matstat.lu.se>, and contributors"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"

[compat]
LinearAlgebra = "1"
PrecompileTools = "1"
SimpleUnPack = "1"
Test = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
